name       : python-setproctitle
version    : 1.2.3
release    : 9
source     :
    - https://github.com/dvarrazzo/py-setproctitle/archive/refs/tags/version-1.2.3.tar.gz : 30aed3179adc96eefcfd646e11c4c819e0dbeb15eb91558f323d264e4775feca
homepage   : https://github.com/dvarrazzo/py-setproctitle
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module to customize the process title
description: |
    The setproctitle module allows a process to change its title (as displayed by system tools such as ps and top). Changing the title is mostly useful in multi-process systems, for example when a master process is forked: changing the children’s title allows to identify the task each process is busy with. The technique is used by PostgreSQL and the OpenSSH Server for example.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
